name: Orbit
version: '1.1'
main: org.warpeak.orbit.Orbit
api-version: '1.21'
softdepend: [WorldEdit, FastAsyncWorldEdit, LuckPerms]

commands:
  orbit:
    description: Управление настройками Orbit
    usage: /orbit reload
    permission: orbit.admin.config
  duelaccept:
    description: Принять дуэль
  dueldecline:
    description: Отклонить дуэль
  duelleave:
    description: Покинуть дуэль
  setlobby:
    description: Установить точку лобби на текущую позицию
  setcase:
    description: Установить кейс префиксов на сундук
  addcoins:
    description: Выдать монеты игроку
    usage: /addcoins <ник> <количество>
    permission: orbit.admin.coins
  removecoins:
    description: Забрать монеты у игрока
    usage: /removecoins <ник> <количество>
    permission: orbit.admin.coins
  settophologram:
    description: Установить голограмму топа на текущую позицию
    usage: /settophologram <kills|coins>
  removetophologram:
    description: Удалить голограмму топа
    usage: /removetophologram <kills|coins>
  purgetopholograms:
    description: Удалить TextDisplay-голограммы в радиусе вокруг игрока
    usage: /purgetopholograms [радиус_в_блоках]
    permission: orbit.admin

permissions:
  orbit.admin:
    description: Полный доступ к административным командам Orbit
    default: op
  orbit.admin.config:
    description: Перезагрузка конфигурации Orbit
    default: op
  orbit.admin.coins:
    description: Доступ к командам выдачи/снятия монет
    default: op
